### ISSUE TITLE
Can I animate my own image?

### ISSUE THREAD

**Issue by mrtpk** [pkhungurn/talking-head-anime-4-demo#4]
I have been trying to create a real-time talking head to interface with chaGPT and stumbled across your repo. Thank you for sharing your work. Instead of an anime character face, if I were to train a student network by giving my photo, would I be able to control animations? I'm a noob in this field and any pointers are greatly appreciated. 
Thanks,
Thomas.

**Comment by pkhungurn** [comment]
Thank you for your interest in my project.

The answer to your question is no. The teacher model does not know how to animate human faces.

**Comment by mrtpk** [comment]
Thank you for getting back to me. This is an amazing work. Please continue to share. Thanks.
